language: csharp
mono: none
dotnet: 3.1.100

dist: xenial
os: linux

script:
- dotnet build ./DotnetBoilerplate.sln -c Release
- dotnet pack -c Release --no-build -o ./packages
- dotnet nuget push ./packages/*.nupkg --api-key $NUGETKEY --source https://api.nuget.org/v3/index.json
