language: csharp
mono: none
dotnet: 3.1.101

os: linux

script:
- dotnet pack DotnetBoilerplate.sln --configuration Release --output nupkgs -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg
- dotnet nuget push nupkgs/*.nupkg -k $NUGETKEY --skip-duplicate